-- Run this script in the Supabase SQL Editor

-- 1. Create PROFILES table
-- This table mirrors the auth.users table but holds our app-specific data
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  website text
);

-- 2. Enable Row Level Security (RLS) for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- 3. Trigger to create a profile automatically on signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. Create TASKS table
create table tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  is_completed boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable RLS for Tasks
alter table tasks enable row level security;

create policy "Individuals can view their own tasks." on tasks
  for select using (auth.uid() = user_id);

create policy "Individuals can create tasks." on tasks
  for insert with check (auth.uid() = user_id);

create policy "Individuals can update their own tasks." on tasks
  for update using (auth.uid() = user_id);

create policy "Individuals can delete their own tasks." on tasks
  for delete using (auth.uid() = user_id);
